### ISSUE TITLE
dnfdragora tracebacks and segfaults if dnf is locked by another application

### ISSUE THREAD

**Issue by kkofler** [anaselli/dnfdragora#6]
Using revision bb6edcf85175a04d9d599ab2754a5e3a6c409ef9.

```
Start looking for groups
Unexpected error: <class 'dnfdaemon.client.DaemonError'>
Traceback (most recent call last):
  File "/usr/bin/dnfdragora", line 33, in <module>
    main_gui = dnfdragora.ui.mainGui(options)
  File "/usr/lib/python3.5/site-packages/dnfdragora/ui.py", line 298, in __init__
    self._fillGroupTree()
  File "/usr/lib/python3.5/site-packages/dnfdragora/ui.py", line 467, in _fillGroupTree
    rpm_groups = self.backend.get_groups()
  File "/usr/lib/python3.5/site-packages/dnfdragora/basedragora.py", line 54, in backend
    return self.get_root_backend()
  File "/usr/lib/python3.5/site-packages/dnfdragora/basedragora.py", line 80, in get_root_backend
    self.backend.ExpireCache()
  File "/usr/lib/python3.5/site-packages/dnfdaemon/client/__init__.py", line 401, in ExpireCache
    rc = self._run_dbus_async('ExpireCache', '()')
  File "/usr/lib/python3.5/site-packages/dnfdaemon/client/__init__.py", line 293, in _run_dbus_async
    result = self._get_result(data)
  File "/usr/lib/python3.5/site-packages/dnfdaemon/client/__init__.py", line 277, in _get_result
    self._handle_dbus_error(user_data['error'])
  File "/usr/lib/python3.5/site-packages/dnfdaemon/client/__init__.py", line 250, in _handle_dbus_error
    raise DaemonError(str(err))
dnfdaemon.client.DaemonError: g-io-error-quark: GDBus.Error:org.baseurl.DnfSystem.LockedError: dnf is locked by another application (36)
<_M_> [ui] YUILoader.cc:104 deleteUI(): Shutting down UI
<ERR> [ui] YUI.cc:94 ~YUI(): 1 open dialogs left over
Segmentation fault (core dumped)
```

**Comment by anaselli** [comment]
yes, i haven't ported the yumex code here, and i need to understand how to manage this using libyui, and to be honest this error helps me to recall i have to unlock the db in case of other crash. The code to force the db unlocking that is in yumex has to be ported as well. Thanks for the reminder.

**Comment by anaselli** [comment]
should be fixed now in current master
